In [1]:
# Que. 1) Write a Numpy program to get the numpy version and show numpy bilds configuration

import numpy as np
print(np.__version__)
print(np.show_config())


1.23.5
blas_armpl_info:
  NOT AVAILABLE
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anaconda3\\Library\\include']
lapack_armpl_info:
  NOT AVAILABLE
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/ProgramData/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/ProgramData/anacond

In [2]:
# Que. 2) Write a Numpy program to get help on the add function

print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

In [15]:
# Que. 3) Write a Numpy program to test whether none of the elements of a given array is zero

import numpy as np
x = np.array([1, 2, 3, 4])
print("Original array:\t", x)

print(np.all(x))

x = np.array([0, 1, 2, 3])
print('Original Array: ', x)

print("Test if none of the elements of the said array is zero")
print(np.all(x))

Original array:	 [1 2 3 4]
True
Original Array:  [0 1 2 3]
Test if none of the elements of the said array is zero
False


In [22]:
arr1 = np.arange(9).reshape(3, 3)
print(arr1)

print(arr1.all())
print(arr1.any())

arr2 = np.array([1, 2, 3, 4])
print(arr2.all())
print(arr2.any())

arr3 = np.array([0, 0, 0, 0])
print(arr3.any())
print(arr3.all())

[[0 1 2]
 [3 4 5]
 [6 7 8]]
False
True
True
True
False
False


In [25]:
# Que. 4) Write a Numpy program to test whether any of the elements of a given array is non-zero

x = np.array([1, 0, 0, 0])
print("Original array:", x)
print("Test whether any of the elements of a given array is non-zero:", np.any(x))

x = np.array([0, 0, 0, 0])
print("Original array:", x)
print("Test whether any of the elements of a given array is non-zero:", np.any(x))


Original array: [1 0 0 0]
Test whether any of the elements of a given array is non-zero: True
Original array: [0 0 0 0]
Test whether any of the elements of a given array is non-zero: False


In [28]:
# Que. 5) Write a Numpy program to test given array element-wise for finiteness (not infinity or nit a number)

# numpy.Inf is a IEEE 754 floating point representation of +ve infinity
# numpy.NAN is a IEEE 754 floating point representation of noa a NUmber (NaN)
# numoy.NINF is a IEEE 754 point representation of -ve infinity

a = np.array([1, 0, np.nan, np.inf])
print("Original Array:", a)
print("Test a given array element-wise for finiteness:", np.isfinite(a))

Original Array: [ 1.  0. nan inf]
Test a given array element-wise for finiteness: [ True  True False False]


In [29]:
# Que. 6) Write a Numpy program to test element-wise for +ve or -ve inifinity

a = np.array([1, 0, np.nan, np.inf])
print("Original Array:", a)
print("Test element-wise for +ve or -ve infinity:", np.isinf(a))

Original Array: [ 1.  0. nan inf]
Test element-wise for +ve or -ve infinity: [False False False  True]


In [30]:
# Que. 7) Write a Numpy program to test element-wise for NaN of a given array

a = np.array([1, 0, np.nan, np.inf])
print("Original Array:", a)
print("Test element-wise for +ve or -ve infinity:", np.isnan(a))

Original Array: [ 1.  0. nan inf]
Test element-wise for +ve or -ve infinity: [False False  True False]


In [44]:
# Que. 8) Write a Numpy program to test element-wise for complex number, real number of a given array. Also test whether a given number is a scalar type or not.

# Note:
# numpy.isscalar(element)(source) 
# is Returns True if the type of element is a scaler type
# Parameters:
# elementany: Input argument, can be of any type and shape
# Returns:
# valbool: True if elelment is a scalar type, False if it is not.

a = np.array([1+1j, 1+0j, 4.5, 3, 2, 2j])
print("Original Array:", a)
print("Checking for complex number:", np.iscomplex(a))

print("Checking for real number:", np.isreal(a))
print("Checking for scalar type:", np.isscalar([3.1]))
print("Checking for scalar type:", np.isscalar(3.1))

Original Array: [1. +1.j 1. +0.j 4.5+0.j 3. +0.j 2. +0.j 0. +2.j]
Checking for complex number: [ True False False False False  True]
Checking for real number: [False  True  True  True  True False]
Checking for scalar type: False
Checking for scalar type: True


In [46]:
a = np.array([4.5, 3, 2, ])  # List
b = (10, 20, 30)  # Tuple
print(np.isscalar(a))  # List
print(np.isscalar(b))  # Tuple
print(np.isscalar(10))  # Integer
print(np.isscalar(10.5))
print(np.isscalar(-10))
print(np.isscalar(True))  # Boolean
print(np.isscalar('Today'))  # String
print(np.isscalar('1+1j'))  # Complex

False
False
True
True
True
True
True
True


In [51]:
# Que. 9) Write a Numpy program to create an element-wise comparison (greater, greater_equal, less and less_equal) of two given arrays.

x = np.array([3, 5])
y = np.array([2, 5])
print("Original numbers: ", x, " & ", y)
print("Comparison - Greater: ", np.greater(x, y))
print("Comparison - Greater_Equal: ", np.greater_equal(x, y))
print("Comparison - less: ", np.less(x, y))
print("COmparison - less_equal: ", np.less_equal(x, y))

Original numbers:  [3 5]  &  [2 5]
Comparison - Greater:  [ True False]
Comparison - Greater_Equal:  [ True  True]
Comparison - less:  [False False]
COmparison - less_equal:  [False  True]


In [64]:
# Que. 10) Write a Numpy program to create an element-wise comparison (equal, equal withis a tolerance) of two given arrays.

x = np.array([72, 79, 85, 90,150, -135, 120, -10, 60, 100])
y = np.array([72, 79, 85, 90, 150, -135, 120, -10, 60, 100.000001])
print("Original numbers: ", x, " & ", y)
print("Comparison - equal", np.equal(x, y))
print("Comparison - equal within a tolerance: ", np.allclose(x, y))

Original numbers:  [  72   79   85   90  150 -135  120  -10   60  100]  &  [  72.         79.         85.         90.        150.       -135.
  120.        -10.         60.        100.000001]
Comparison - equal [ True  True  True  True  True  True  True  True  True False]
Comparison - equal within a tolerance:  True


In [70]:
# Que. 11) Write a Numpy program to create an array with the values 1, 7, 13, 105 and determine the size of the memory occupies by the array.

x = np.array([1, 7, 13, 105])
print("Original Array: ", x)
print("Size of the memory occupied by the said array: ")
print("%d bytes " %(x.size * x.itemsize))

Original Array:  [  1   7  13 105]
Size of the memory occupied by the said array: 
16 bytes 


In [79]:
# Que. 12) Write a Numpy program to create an array of 10 zeros, 10 ones, 10 fives.

zarray = np.zeros(10)
oarray = np.ones(10)
farray = np.ones(10) * 5
print("An array of 10 zeros: ", zarray)
print("An array of 10 ones: ", oarray)
print("An array of 10 fives: ", farray)

array = ([zarray, oarray, farray])
print("An array of all mix: ", array)

An array of 10 zeros:  [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
An array of 10 ones:  [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
An array of 10 fives:  [5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
An array of all mix:  [array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]), array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])]


In [89]:
# Que. 13) Write a Numpy program to create an array of the integers from 30 to 70.

array = np.arange(30, 71)
print("Array of the integers from 30 to 70 : ", array)

Array of the integers from 30 to 70 :  [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70]


In [90]:
# Que. 14) Write a Numpy program to create an array of all the even integers from 30 to 70.

array = np.arange(30, 71, 2)
print("Array of all the even integers from 30 to 70 : ", array)

Array of all the even integers from 30 to 70 :  [30 32 34 36 38 40 42 44 46 48 50 52 54 56 58 60 62 64 66 68 70]
