In [1]:
# Load the Excel
# C:\\Users\\vijay\\Downloads\\MachineLeaninig\\Day_6\\Data Preprocessing Data File.xlsx
# Formula, Y = mx + c

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import os

In [2]:
# Load data set

os.chdir("C:\\Users\\vijay\\Downloads\\MachineLeaninig\\Day_6\\")
df1 = pd.read_excel("Data Preprocessing Data File.xlsx")
print(df1)

   Country   Age   Salary  Purchased 
0   France   44.0  72000.0         No
1       NaN  27.0  48000.0        Yes
2  Germany    NaN  54000.0         No
3    Spain   39.0      NaN         No
4  Germany    NaN  64000.0        Yes
5   France   35.0  58000.0        Yes
6    Spain   39.0  52000.0         No
7   France   48.0      NaN        Yes
8  Germany   50.0  83000.0         No
9   France   37.0  67000.0        Yes


In [3]:
# load independent variable and dependent variable to two separate arrays
# Columns Independent variable - Country, Age, Salary
# Dependent Variable - Purchased

# Create X
x = df1.iloc[:,:-1].values
print(x)

[['France ' 44.0 72000.0]
 [nan 27.0 48000.0]
 ['Germany ' nan 54000.0]
 ['Spain ' 39.0 nan]
 ['Germany ' nan 64000.0]
 ['France ' 35.0 58000.0]
 ['Spain ' 39.0 52000.0]
 ['France ' 48.0 nan]
 ['Germany ' 50.0 83000.0]
 ['France ' 37.0 67000.0]]


In [4]:
# Create Y
y = df1.iloc[:, 3].values
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [5]:
# Missing value treatment - Impute Values
# Country - Most Frequent

from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan, strategy = 'most_frequent')
imputer = imputer.fit(x[:,0:1])
x[:, 0:1] = imputer.transform(x[:,0:1])
print(x)

[['France ' 44.0 72000.0]
 ['France ' 27.0 48000.0]
 ['Germany ' nan 54000.0]
 ['Spain ' 39.0 nan]
 ['Germany ' nan 64000.0]
 ['France ' 35.0 58000.0]
 ['Spain ' 39.0 52000.0]
 ['France ' 48.0 nan]
 ['Germany ' 50.0 83000.0]
 ['France ' 37.0 67000.0]]


In [7]:
# Missing value treatment - Impute Values
# Age - Constant

imputer = SimpleImputer(missing_values = np.nan, strategy = 'constant', fill_value = 40)
imputer = imputer.fit(x[:,1:2])
x[:,1:2] = imputer.transform(x[:,1:2])
print(x)

[['France ' 44.0 72000.0]
 ['France ' 27.0 48000.0]
 ['Germany ' 40 54000.0]
 ['Spain ' 39.0 nan]
 ['Germany ' 40 64000.0]
 ['France ' 35.0 58000.0]
 ['Spain ' 39.0 52000.0]
 ['France ' 48.0 nan]
 ['Germany ' 50.0 83000.0]
 ['France ' 37.0 67000.0]]


In [8]:
# Missing value treatment - Impute Values
# Salary - Mean

imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
imputer = imputer.fit(x[:,2:3])
x[:,2:3] = imputer.transform(x[:,2:3])
print(x)

[['France ' 44.0 72000.0]
 ['France ' 27.0 48000.0]
 ['Germany ' 40 54000.0]
 ['Spain ' 39.0 62250.0]
 ['Germany ' 40 64000.0]
 ['France ' 35.0 58000.0]
 ['Spain ' 39.0 52000.0]
 ['France ' 48.0 62250.0]
 ['Germany ' 50.0 83000.0]
 ['France ' 37.0 67000.0]]


In [11]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder
label_x = LabelEncoder()
x[:,0] = label_x.fit_transform(x[:, 0])
print(x)

[[0 44.0 72000.0]
 [0 27.0 48000.0]
 [1 40 54000.0]
 [2 39.0 62250.0]
 [1 40 64000.0]
 [0 35.0 58000.0]
 [2 39.0 52000.0]
 [0 48.0 62250.0]
 [1 50.0 83000.0]
 [0 37.0 67000.0]]


In [12]:
# One hot Encoding/ Column Transformation

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(transformers = [('encoder', OneHotEncoder(), [0])], remainder = 'passthrough')

x = np.array(ct.fit_transform(x))
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [1.0 0.0 0.0 27.0 48000.0]
 [0.0 1.0 0.0 40 54000.0]
 [0.0 0.0 1.0 39.0 62250.0]
 [0.0 1.0 0.0 40 64000.0]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 39.0 52000.0]
 [1.0 0.0 0.0 48.0 62250.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [13]:
# Label Encoding Y

label_y = LabelEncoder()
y = label_y.fit_transform(y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [14]:
# Standardization

from sklearn.preprocessing import StandardScaler
std_sca = StandardScaler()

x_STD = std_sca.fit_transform(x)
print(pd.DataFrame(x_STD))

     0         1    2         3         4
0  1.0 -0.654654 -0.5  0.660861  1.002707
1  1.0 -0.654654 -0.5 -2.079293 -1.465494
2 -1.0  1.527525 -0.5  0.016119 -0.848444
3 -1.0 -0.654654  2.0 -0.145067  0.000000
4 -1.0  1.527525 -0.5  0.016119  0.179973
5  1.0 -0.654654 -0.5 -0.789809 -0.437077
6 -1.0 -0.654654  2.0 -0.145067 -1.054127
7  1.0 -0.654654 -0.5  1.305603  0.000000
8 -1.0  1.527525 -0.5  1.627974  2.133965
9  1.0 -0.654654 -0.5 -0.467438  0.488498


In [15]:
# Normalization - MinMaxScaler

from sklearn.preprocessing import MinMaxScaler

nm_x = MinMaxScaler()
x_NOR = nm_x.fit_transform(x)
print(pd.DataFrame(x_NOR))

     0    1    2         3         4
0  1.0  0.0  0.0  0.739130  0.685714
1  1.0  0.0  0.0  0.000000  0.000000
2  0.0  1.0  0.0  0.565217  0.171429
3  0.0  0.0  1.0  0.521739  0.407143
4  0.0  1.0  0.0  0.565217  0.457143
5  1.0  0.0  0.0  0.347826  0.285714
6  0.0  0.0  1.0  0.521739  0.114286
7  1.0  0.0  0.0  0.913043  0.407143
8  0.0  1.0  0.0  1.000000  1.000000
9  1.0  0.0  0.0  0.434783  0.542857


In [17]:
# Normalization

from sklearn.preprocessing import Normalizer

nm_x = Normalizer()
x_NOR = nm_x.fit_transform(x)
print(pd.DataFrame(x_NOR))

          0         1         2         3    4
0  0.000014  0.000000  0.000000  0.000611  1.0
1  0.000021  0.000000  0.000000  0.000562  1.0
2  0.000000  0.000019  0.000000  0.000741  1.0
3  0.000000  0.000000  0.000016  0.000627  1.0
4  0.000000  0.000016  0.000000  0.000625  1.0
5  0.000017  0.000000  0.000000  0.000603  1.0
6  0.000000  0.000000  0.000019  0.000750  1.0
7  0.000016  0.000000  0.000000  0.000771  1.0
8  0.000000  0.000012  0.000000  0.000602  1.0
9  0.000015  0.000000  0.000000  0.000552  1.0


In [20]:
# Model Creation 
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x_NOR, y, test_size = 0.2)
print(pd.DataFrame(x_train), y_train)

          0         1         2         3    4
0  0.000000  0.000016  0.000000  0.000625  1.0
1  0.000016  0.000000  0.000000  0.000771  1.0
2  0.000017  0.000000  0.000000  0.000603  1.0
3  0.000021  0.000000  0.000000  0.000562  1.0
4  0.000000  0.000000  0.000016  0.000627  1.0
5  0.000015  0.000000  0.000000  0.000552  1.0
6  0.000000  0.000000  0.000019  0.000750  1.0
7  0.000000  0.000012  0.000000  0.000602  1.0 [1 1 1 1 0 1 0 0]
