In [2]:
# Numoy
# Array
import numpy as np
array1 = np.array([10, 12, 14, 16, 20])
print(array1)

[10 12 14 16 20]


In [4]:
# 2d Array
list1 = [[10, 20, 30], [50, 60, 70]]
print(list1)
a = np.array([[10, 20, 30], [50, 60, 70]])
print(a)

[[10, 20, 30], [50, 60, 70]]
[[10 20 30]
 [50 60 70]]


In [9]:
# Array with different number of elements

arr1 = np.array([[10, 20, 40], [50, 60, 70, np.nan]])
print(arr1)

[list([10, 20, 40]) list([50, 60, 70, nan])]


C:\Users\vijay\AppData\Local\Temp\ipykernel_336\1788238187.py:3: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  arr1 = np.array([[10, 20, 40], [50, 60, 70, np.nan]])


In [15]:
list1 = [[10, 20, 30], [50, 60, 70, 80]]
print(list1)

[[10, 20, 30], [50, 60, 70, 80]]


In [20]:
a = np.array([[10, 20, 30], [50, 60, 70, 80]])
print(a)
print(type(a))

[list([10, 20, 30]) list([50, 60, 70, 80])]
<class 'numpy.ndarray'>


C:\Users\vijay\AppData\Local\Temp\ipykernel_336\3439017238.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[10, 20, 30], [50, 60, 70, 80]])


In [26]:
list1 = [10, 20, 30, 40, 50]
array1 = np.array(list1)
print("type of array1:\t\t",type(array1))
print("type of list1:\t\t",type(list1))
print("values of array1:\t",array1)

type of array1:		 <class 'numpy.ndarray'>
type of list1:		 <class 'list'>
values of array1:	 [10 20 30 40 50]


In [28]:
list1 = [10,20,30,40,50,'X']
array1 = np.array (list1)
print (type(array1))
print (type(list1))
print (list1)
print (array1)

<class 'numpy.ndarray'>
<class 'list'>
[10, 20, 30, 40, 50, 'X']
['10' '20' '30' '40' '50' 'X']


In [33]:
# with tuple
Tup1 = (10, 20, 30, 40, 50, 'x', 'y')

array1 = np.array(Tup1)
print("type of Tup1:\t\t",type(Tup1))
print("type of array1:\t\t",type(array1))
print("values of Tup1:\t\t",Tup1)
print("values of array1:\t",array1)

type of Tup1:		 <class 'tuple'>
type of array1:		 <class 'numpy.ndarray'>
values of Tup1:		 (10, 20, 30, 40, 50, 'x', 'y')
values of array1:	 ['10' '20' '30' '40' '50' 'x' 'y']


In [36]:
# Changes in the sub list won't impact main list
list1 = [10, 20, 30, 40, 50, 60, 70, 80]
list2 = list1[:3]
print(list2)
list2[1] = 500
print(list2)
print(list1)

[10, 20, 30]
[10, 500, 30]
[10, 20, 30, 40, 50, 60, 70, 80]


In [37]:
# If we update sliced array, parent array also gets impacted
array1 = np.array(list1)
print(array1)
array2 = array1[:3]
print(array2)
array2[0] = 500
print(array1)
print(array2)

[10 20 30 40 50 60 70 80]
[10 20 30]
[500  20  30  40  50  60  70  80]
[500  20  30]


In [38]:
# But in copy parent array won't impacted
print(array1)
array2 = (array1[0:3]).copy()
print(array2)
array2[1] = 200
print(array1)
print(array2)

[500  20  30  40  50  60  70  80]
[500  20  30]
[500  20  30  40  50  60  70  80]
[500 200  30]


In [39]:
# Matrix
a = np.arange(9)
a = a.reshape((3,3))
print(a)
print(a[1][1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
4


In [45]:
b = np.zeros((5, 5))
b = np.ones((3,5))
print(b)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [47]:
# F for columns, C for rows
mat1 = np.arange(0, 30)
mat2 = np.reshape(mat1, (6, 5), 'F')
print(mat1)
print("\n",mat2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

 [[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


In [48]:
# Create Matrix from Three List and Transpose

list1 = [10, 20, 30, 40]
list2 = [100, 110, 120, 130]
list3 = [200, 210, 220, 230]
Mat1 = np.array([list1, list2, list3])
print(Mat1)
print("\n", Mat1.T)

[[ 10  20  30  40]
 [100 110 120 130]
 [200 210 220 230]]

 [[ 10 100 200]
 [ 20 110 210]
 [ 30 120 220]
 [ 40 130 230]]


In [49]:
a = np.array([])
print(a)

[]


In [50]:
a = np.array([10, 20, 30])
print(a)

[10 20 30]


In [52]:
a = np.array([10, 20.5, 30])
print(a)

[10.  20.5 30. ]


In [53]:
a = np.array([10, 20.5, 'Sun', 30])
print(a)

['10' '20.5' 'Sun' '30']


In [54]:
a = np.array([10, 20.5, False, True, 30])
print(a)

[10.  20.5  0.   1.  30. ]


In [55]:
array1 = np.array([10, 12, 14, 16, 20])
print(array1)

[10 12 14 16 20]


In [56]:
a = np.array([10, 20, 30])
print(a)

[10 20 30]


In [57]:
a.ndim

1

In [62]:
a = np.array([[10, 20, 30], [45, 42, 35]])
print(a)

[[10 20 30]
 [45 42 35]]


In [59]:
a.ndim

2

In [60]:
a = np.array([[10, 20, 30], [45, 35]])
print(a)

[list([10, 20, 30]) list([45, 35])]


C:\Users\vijay\AppData\Local\Temp\ipykernel_336\380345149.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  a = np.array([[10, 20, 30], [45, 35]])


In [66]:
list1 = [[10, 20, 30], [50, 60, 70, 80]]
print(list1)

[[10, 20, 30], [50, 60, 70, 80]]


In [64]:
np.array(list1)

C:\Users\vijay\AppData\Local\Temp\ipykernel_336\3495724499.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  np.array(list1)


array([list([10, 20, 30]), list([50, 60, 70, 80])], dtype=object)

In [67]:
a = np.array([[10, 20, 30], [45, 0, 35]])
print(a)

[[10 20 30]
 [45  0 35]]


In [68]:
a = np.array([[10, 20, 30], [45, np.nan, 35]])
print(a)

[[10. 20. 30.]
 [45. nan 35.]]


In [69]:
Tup1 = (10, 20, 30, 40, 50, 'x', 'y')
array1 = np.array(Tup1)
print(type(array1))
print(type(Tup1))
print(Tup1)
print(array1)

<class 'numpy.ndarray'>
<class 'tuple'>
(10, 20, 30, 40, 50, 'x', 'y')
['10' '20' '30' '40' '50' 'x' 'y']


In [70]:
a = np.array([10, 20, 30])
b = a
b

array([10, 20, 30])

In [71]:
b[1] = 222
print(a)
print(b)

[ 10 222  30]
[ 10 222  30]


In [72]:
a = np.array([10, 20, 30])
b = a.copy()
b[1] =  222
print(a)
print(b)

[10 20 30]
[ 10 222  30]


In [73]:
a = np.arange(9)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [74]:
a = np.arange(10, 20, 2)
a

array([10, 12, 14, 16, 18])

In [75]:
a = np.arange(10, 100, 10)
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [76]:
a = np.arange(9)
a = a.reshape((3, 3))
print(a)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [79]:
a = np.arange(30)
print(a)

a = a.reshape((6, 5))
print("\n",a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [81]:
a = np.arange(30)
print(a)

a = a.reshape((3, 10))
print("\n",a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]]


In [82]:
a = np.arange(30)
a = a.reshape((2, 5, 3))
print(a)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [83]:
b = np.zeros((5, 5))
b

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [84]:
b = np.ones((5, 5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [85]:
b * 5

array([[5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.],
       [5., 5., 5., 5., 5.]])

In [87]:
b = np.ones((5, 5))
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [88]:
mat1 = np.arange(0, 30)
mat1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [89]:
mat2 = np.reshape(mat1, (6, 5), 'F')
print(mat2)

[[ 0  6 12 18 24]
 [ 1  7 13 19 25]
 [ 2  8 14 20 26]
 [ 3  9 15 21 27]
 [ 4 10 16 22 28]
 [ 5 11 17 23 29]]


In [90]:
mat2 = np.reshape(mat1, (6, 5), 'C')
print(mat2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [91]:
mat2 = np.reshape(mat1, (2, 5, 3), 'F')
print(mat2)

[[[ 0 10 20]
  [ 2 12 22]
  [ 4 14 24]
  [ 6 16 26]
  [ 8 18 28]]

 [[ 1 11 21]
  [ 3 13 23]
  [ 5 15 25]
  [ 7 17 27]
  [ 9 19 29]]]


In [92]:
mat2 = np.reshape(mat1, (2, 5, 3), 'C')
print(mat2)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [93]:
mat2 = np.reshape(mat1, (2, 5, 3))
print(mat2)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]
  [12 13 14]]

 [[15 16 17]
  [18 19 20]
  [21 22 23]
  [24 25 26]
  [27 28 29]]]


In [94]:
mat2 = np.reshape(mat1, (6, 5), 'C')
print(mat2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]


In [95]:
mat2.T

array([[ 0,  5, 10, 15, 20, 25],
       [ 1,  6, 11, 16, 21, 26],
       [ 2,  7, 12, 17, 22, 27],
       [ 3,  8, 13, 18, 23, 28],
       [ 4,  9, 14, 19, 24, 29]])

In [96]:
# Que. 1) Write Python program to sum all the items in a list

def sum_list(items):
    sum_numbers = 0
    for x in items:
        sum_numbers += x
    return sum_numbers

print(sum_list([1, 2, -8]))

-5


In [97]:
# Que. 2) Write Python program to multiplies all the itemsin a list

def multiply_list(items):
    tot = 1
    for x in items:
        tot *= x
    return tot

print(multiply_list([1, 2, -8]))

-16


In [98]:
# Que. 3) Write Python program to get the largest numbers from a list

def max_num_in_list(list):
    max = list[0]
    for a in list:
        if a > max:
            max = a
    return max

print(max_num_in_list([1, 2, -8, 0]))

2


In [99]:
# Que. 4) Write Python program to get the smallest number from a list

def smallest_num_in_list(list):
    min = list[0]
    for a in list:
        if a < min:
            min = a
    return min

print(smallest_num_in_list([1, 2, -8, 0]))

-8


In [100]:
# Que. 5) Write Python program to count the numbers of strings where the
# string length is 2 or more and the first and last character are same
# from a given list of strings.
# sample list : ['abc', 'xyz', 'abc', '1221']
# Expected Result: 2

def match_words(words):
    ctr = 0
    
    for word in words:
        if len(word) > 1 and word[0] == word[-1]:
            ctr += 1
    return ctr

print(match_words(['abc', 'xyz', 'aba', '1221']))

2


In [ ]:
# Que. 6) Write Python program to get a list, sorted in increasing order by
# the last element in each tuple from a given list of non-empty tuples.
# sample list : [(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]
# Expected Result: [(2, 1), (1, 2), (2, 3), (4, 4), (2, 5)]



In [114]:
# Example 1

In [113]:
x = [2, 8, 1, 4, 6, 3, 7]

print("Sorted list returned: ", sorted(x))

Sorted list returned:  [1, 2, 3, 4, 6, 7, 8]


In [104]:
print("Reverse sort:\t", sorted(x, reverse = True))

Reverse sort:	 [8, 7, 6, 4, 3, 2, 1]


In [105]:
# Dictionary
x = {'q' : 1, 'w' : 2, 'e' : 3, 'r' : 4, 't' : 5, 'y' : 6}
print("sorted:", sorted(x))

sorted: ['e', 'q', 'r', 't', 'w', 'y']


In [109]:
# Set 
x = {'q', 'w', 'e', 'r', 't', 'y'}
print("sorted:\t\t",sorted(x), 
      "\nReverse sorted:\t",sorted(x, reverse = True))

sorted:		 ['e', 'q', 'r', 't', 'w', 'y'] 
Reverse sorted:	 ['y', 'w', 't', 'r', 'q', 'e']


In [112]:
# Frozen set
x = frozenset(('q', 'w', 'e', 'r', 't', 'y'))
print(sorted(x))

['e', 'q', 'r', 't', 'w', 'y']


In [116]:
# Example 2 - sort based on length of string
L = ["cccc", "b", "dd", "aaa"]
print("Normal sort:\t", sorted(L))
print("Sort with len:\t", sorted(L, key = len))

Normal sort:	 ['aaa', 'b', 'cccc', 'dd']
Sort with len:	 ['b', 'dd', 'aaa', 'cccc']


In [117]:
 # Example 3 - sort based on user defined function
    
def func(x):
    return x % 7

L = [15, 3, 11, 7]

print("Normal sort:", sorted(L))
print("Sorted with key:", sorted(L, key = func))

Normal sort: [3, 7, 11, 15]
Sorted with key: [7, 15, 3, 11]


In [118]:
# Que. 3) Ans:

def last(n):
    return n[-1]

def sort_list_last(tuples):
    return sorted(tuples, key = last)

print(sort_list_last([(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)]))

[(2, 1), (1, 2), (2, 3), (4, 4), (2, 5)]


In [123]:
# Que. 7) Write Python program to remove duplicates from a list

a = [10, 20, 30, 20, 10, 50, 60, 40, 80, 50, 40]

dup_items = set()
uniq_items = []
for x in a:
    if x not in dup_items:
        uniq_items.append(x)
        dup_items.add(x)
print(dup_items)

{40, 10, 80, 50, 20, 60, 30}


In [124]:
# Que. 8) Write Python program to check a list is empty or not

l = []
if not l:
    print("List is empty")

List is empty


In [125]:
# Que. 9) Write Python program to clone or copy a list

# Answer 1:
original_list = [10, 22, 44, 23, 4]
new_list = list(original_list)
print(original_list)
print(new_list)

[10, 22, 44, 23, 4]
[10, 22, 44, 23, 4]


In [126]:
# Answer 2:
original_list = [10, 22, 44, 23, 4]
new_list = original_list.copy()
print(original_list)
print(new_list)

[10, 22, 44, 23, 4]
[10, 22, 44, 23, 4]


In [128]:
# Que. 10) Write Python program to find the list of words that are longer
# than n from a given list of words

def long_word(n, str):
    word_len = []
    txt = str.split(" ")
    for x in txt:
        if len(x) > n:
            word_len.append(x)
    return word_len

print(long_word(3, "The quick brown for jumps over the lazy dog"))

['quick', 'brown', 'jumps', 'over', 'lazy']


In [136]:
# Que. 11) Write Python program that takes two lists and returns Ture if
# they have at least one common member

def common_data(list1, list2):
    result = False
    for x in list1:
        for y in list2:
            if x == y:
                result = True
                return result

print(common_data([1, 2, 3, 4, 5], [5, 6, 7, 8, 9]))
print(common_data([1, 2, 3, 4, 5], [6, 7, 8, 9]))

True
None


In [138]:
# Que. 12) Write Python program to print a specified list after removing the
# the 0th, 4th, and 5th elements.
# Sample List : ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow']
# Expected Output : ['Green', 'White', 'Black']

color = ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow']
color = [x for (i, x) in enumerate(color) if i not in (0, 4, 5)]
print(color)

['Green', 'White', 'Black']


In [139]:
# enumerate Example

l1 = ["eat", "sleep", "repeat"]
s1 = "geek"

# Creating enumerate objects

obj1 = enumerate(l1)
obj2 = enumerate(s1)
print(obj1)
print(obj2)

In [140]:
print(list(enumerate(l1)))

[(0, 'eat'), (1, 'sleep'), (2, 'repeat')]


In [141]:
print(list(enumerate(s1)))

[(0, 'g'), (1, 'e'), (2, 'e'), (3, 'k')]


In [142]:
# Changing start index to 2 from 0

print(list(enumerate(s1, 2)))

[(2, 'g'), (3, 'e'), (4, 'e'), (5, 'k')]
